version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=spp
      - POSTGRES_USER=spp
      - POSTGRES_DB=spp
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 5432:5432     