create table payment_file (
                              id int4 generated by default as identity,
                              payment varchar(255),
                              primary key (id)
)